### ISSUE TITLE
Can we make sure words don't break in the middle?

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/data-stories#71]
![Screenshot 2022-02-23 at 13 57 27](https://user-images.githubusercontent.com/1473244/155333680-02f9bea7-547e-4cfc-b5d1-724364273f08.png)

**Comment by fquellec** [comment]
Fixed in #197

**Comment by alexbfree** [comment]
Reopening - see article list pages where this is still occurring:

![Screenshot 2022-03-21 at 15 38 39](https://user-images.githubusercontent.com/1473244/159296895-6024f415-2369-4e94-b79b-9d3e4faa32aa.png)
